### ISSUE TITLE
mzR::openIDfile

### ISSUE THREAD

**Issue by lgatto** [vladpetyuk/MSnID#1]
Would you consider a patch to support `mzR::openIDfile` to read the ident files. It is really fast!

**Comment by vladpetyuk** [comment]
I definitely keep this in mind.

**Comment by lgatto** [comment]
Also, I think it would be useful to support identification data as input, in addition to file names.

**Comment by vladpetyuk** [comment]
It looks like `mzR::openIDfile` does not report "scan number(s)".  Note they are different from spectrumIDs or aqcuisitionNum.  Perhaps I can ignore this issue for now since *usually* they are not used in the pipeline.

**Comment by vladpetyuk** [comment]
"IsotopeError" is another item missing in `mzR::openIDfile` `mzRident` object

**Comment by vladpetyuk** [comment]
it is supported now with backend="mzR" option for read_mzIDs

**Comment by lgatto** [comment]
Great, thanks for this. This will be useful next time I need to tackle many id files.

**Comment by vladpetyuk** [comment]
Feel free to open a separate issue.  I'll probably come up with a method
that dispatches on mzRident object.
