### ISSUE TITLE
More robust way of evaluating filter expression in `apply_filter`

### ISSUE THREAD

**Issue by aoles** [vladpetyuk/MSnID#5]
Hi Vlad,
I've recently run into an error related to non-standard evaluation in your `apply_filter` method. The problem appeared when building the Bioconductor "proteomics" workflow vignette by a call to `rmarkdown::render` from inside of another function, see at the bottom of http://docbuilder.bioconductor.org:8080/job/proteomics/20/label=master/console

It appears to me that this is some sort of scoping issue caused by the fact that `eval(exprssn)` evaluates `exprssn` in the calling environment, in this case your `apply_filter` method. Things seem to work fine provided that the objects are defined in the global environment, which is usually the case when working interactively, or for code chunks inside a vignette. However, things break once the `rmarkdown::render` function is called from another function, which is the case for the BioC workflow builder scripts. This is because by default `render` evaluates code chunks in its calling environment and not in the global environment; in such a case object names from the expression passed to the `apply_filter` method are not resolved properly.

The workaround which I've implemented on the BioC workflow builders is to run `render` in the global environment by specifying `envir = parent.frame(2L)`. However, it would be good to make your code bullet proof in first place. I've already tried replacing the following line in **R/MSnID-methods.R**

``` r
msnidObj@psms <- msnidObj@psms[eval(exprssn),]
```

by

``` r
msnidObj@psms <- msnidObj@psms[eval(exprssn, msnidObj@psms, parent.frame()),]
```

but strangely enough, this doesn't seem to make any difference. I would expect that specifying the enclosing environments should alleviate the issue, but somehow this doesn't work as expected.

Any thoughts?

Cheers,
Andrzej

**Comment by vladpetyuk** [comment]
Hi Andrzej,
Thanks for taking a look into it.  This is certainly something I have not ran into before.

1. Could you come up with a minimal test case that recapitulates the problem? This would be helpful for me to fully understand and address the problem.
2. Any suggestions on how to handle this type of case?  I thought it is convenient to pass expressions as strings and then simply eval(parse(text=.)). Perhaps evaluating within `msnidObj@psms`? Or passing expressions as strings not a good idea at all?

Cheers,
Vlad

**Comment by aoles** [comment]
Hi Vlad,
thanks for getting back to me so quickly!

Here is how to reproduce the isue. Consider the following **MSnID.Rmd** file:

    ---
    output: html_document
    ---
    
    ```{r}
    library(MSnID)
    
    data(c_elegans)
    
    msnid <- assess_termini(msnidObj, validCleavagePattern="[KR]\\.[^P]")
    
    msnid <- apply_filter(msnid, "numIrregCleavages == 0")
    summary(mass_measurement_error(msnid))
    
    msnid <- apply_filter(msnid, "abs(mass_measurement_error(msnid)) < 20")
    summary(mass_measurement_error(msnid))
    ```

It compiles just fine with `rmarkdown::render("MSnID.Rmd")`. However, when I try to run `render` from another function I get an error.

```r
rm(list=ls()) #make sure we run in a clean environment
f <- function(file) rmarkdown::render(file)
f("MSnID.Rmd")
```
```
processing file: MSnID.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1
Quitting from lines 6-17 (MSnID.Rmd) 
Error in mass_measurement_error(msnid) : object 'msnid' not found
```
Thank you for looking into this!
Andrzej

**Comment by vladpetyuk** [comment]
When I wrote this method the intention was that it evaluates within `msnid@psms` environment.  So the parent ion mass measurement error filter should be implemented like this.

```r
---
output: html_document
---

```{r}
library(MSnID)

data(c_elegans)

msnid <- assess_termini(msnidObj, validCleavagePattern="[KR]\\.[^P]")

msnid <- apply_filter(msnid, "numIrregCleavages == 0")
summary(mass_measurement_error(msnid))

msnid$absParentMassErrorPPM <- abs(mass_measurement_error(msnid))
msnid <- apply_filter(msnid, "absParentMassErrorPPM < 20")
# msnid <- apply_filter(msnid, "abs(mass_measurement_error(msnid)) < 20")
summary(mass_measurement_error(msnid))
```
```

However, there are cases when I evaluate based on objects present in the global environment.  I'll take a look how to make it working.

Thanks for pointing,
Vlad

**Comment by aoles** [comment]
Thanks Vlad! I had a second look into how the scoping is resolved when evaluating code chunks in `render`, and honestly, I'm quite puzzled why your current implementation doesn't work.

In my previous example, when I run the following code inside of `apply_filter` method the `msnid` object is listed regardless of the way `render` gets invoked.

```r
envir <- parent.frame()
ls(envir)
```
Yet, when I try running `msnidObj@psms <- msnidObj@psms[eval(exprssn, envir),]`, it complains about not finding `msnid` if `render` is called from another function. Weird...

**Comment by vladpetyuk** [comment]
Another weird thing is that I can't really debug the method.  I can't print anything after breaking in with a `trace`.

```r
rm(list=ls()) #make sure we run in a clean environment
f <- function(file) rmarkdown::render(file)

trace("apply_filter", tracer=browser, exit=browser,
      signature=c("MSnID","character"), 
      where=asNamespace("MSnID"))

f("MSnID.Rmd")

untrace("apply_filter", 
        signature=c("MSnID","character"), 
        where=asNamespace("MSnID"))
```

**Comment by aoles** [comment]
That's because apparently *rmarkdown/knitr* captures the console output. Not sure how this can be circumvented, in my debugging attempts I just used the approach of altering the original `apply_filter` function to return some debug info, like the content of ls(), and printed it in the resulting output html file. 

But as I said, maybe there is a better, ideally interactive way of doing this when running `render`. @yihui might have some advice on best practices in debugging such beasts.

**Comment by yihui** [comment]
When you are debugging in a browser context, the normal console output can be resumed after `sink()`, which stops knitr from capturing the `stdout`.

**Comment by aoles** [comment]
Sweet, thanks @yihui!

**Comment by vladpetyuk** [comment]
Thanks @yihui ! Now how do I get to the environment of the Rmd file?  Starting with `environment()` and walking upstream with `parent.env()` didn't get me to the variable I was looking for - `peps2keep`.  I apologize for not knowing "nuts and bolts" of this.  If you can point me to the right manual to read on how to get to the variable of the Rmd environment that would be helpful.

**Comment by yihui** [comment]
`knitr:::knit_global()` is knitr's "global" environment, which is exactly the `envir` argument of `rmarkdown::render()`.

**Comment by vladpetyuk** [comment]
One way to make it work is to call `attach(parent.frame())`
right before command calling evaluation of filter expression.
Not sure if this is a proper approach.  I'll keep thinking about it.

**Comment by vladpetyuk** [comment]
Here is another and more robust way.  I need to double check to make sure it does not take a toll on performance.
```r
function (msnidObj, filterObj) 
{
    exprssn <- parse(text = filterObj, srcfile = NULL, keep.source = FALSE)
    idx <- eval(exprssn, envir = msnidObj@psms, enclos = parent.frame())
    msnidObj@psms <- msnidObj@psms[idx,]
    return(msnidObj)
}
```
This is pretty much along the idea you had.  I think the problem was that `[.data.frame` is not a function (which is 178 lines long) does something with environments that interfered with what you proposed.

**Comment by aoles** [comment]
Great, thanks Vlad for following up on this and for suggesting a solution fixing the issue! I don't see any obvious reasons why it could affect performance, but double checking is a good idea.

Cheers,
Andrzej

**Comment by vladpetyuk** [comment]
Addressed with commit:
https://github.com/vladpetyuk/MSnID/commit/2fb4e7905f23891d659dd5a6203b8e21b1477b71
